language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t f3ar161/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true f3ar161/docker-react npm run test
